#!/bin/sh

command='bin/nolo-gmetric'
expected='usage: nolo-gmetric [path-to-plugin]'
actual=`$command`

if ! [ "${actual}" = "${expected}" ]; then
  echo "${command} failed! Got \"${actual}\", but expected \"${expected}\""
  exit -1
fi
