#!/bin/sh

# pending
#echo '- Pending'; exit

command='bin/nolo-gmetric -n plugins/test/multiple'
expected=$(cat <<EOF
gmetric --name="guage" --value="999"
gmetric --name="counter" --value="5"
EOF)
actual=`$command`

if ! [ "${actual}" = "${expected}" ]; then
  echo "${command} failed! Got \"${actual}\", but expected \"${expected}\""
  exit -1
fi
