#!/bin/sh

PATH="test/fake/bin:$PATH"
command='plugins/passenger'
expected=$(cat <<EOF
max_pool_size 7 units=processes slope=both description="Max processes in Passenger pool"
open_processes 3 units=processes slope=both description="Number of currently open passenger processes"
active_processes 0 units=processes slope=both description="Number of active passenger processes"
inactive_processes 3 units=processes slope=both description="Number of inactive passenger processes"
global_queue_depth 0 units=requests slope=both description="Requests waiting on a free process"
memory_usage 730.52 units=MB slope=both description="Passenger Memory usage"
EOF)
actual=`$command`

if ! [ "${actual}" = "${expected}" ]; then
  echo "${command} failed! Got:"
  echo "${actual}"
  echo
  echo "but expected:"
  echo "${expected}"
  exit -1
fi
